/*
 * File: app/view/MyViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyViewport', {
    extend: 'Ext.container.Viewport',

    autoScroll: true,
    layout: {
//    	width:550,
//        height: 600,
        type: 'fit'
    },

    initComponent: function() {
        var me = this;
        alert();
        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                	width:550,
                	height: 600,
                    autoShow: true,
                    autoScroll: true,
                    layout: {
                        type: 'border'
                    },
                    title: 'Order',
                    items: [
                        {
                            xtype: 'panel',
                            region: 'north',
                            height: 150,
                            width:550,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            //title: 'headpanel',
                            collapsible: true,
                            items: [
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    height: 150,
                                    width: 150,
                                    title: 'Info'
                                },
                                {
                                    xtype: 'panel',
                                    flex: 1,
                                    height: 150,
                                    width: 400,
                                    title: 'Order Details'
                                }
                            ]
                        }
                        
                        ,

                        {
                            xtype: 'panel',
                            region: 'center',
                            height: 450,
                            width:550,
                            layout: {
                                align: 'stretch',
                                type: 'hbox'
                            },
                            //title: 'bodypanel',
                            title:'',
                            //collapsible: true,
                            items: [
                                    {
                                        xtype: 'panel',
                                        height: 450,
                                        width: 100,
                                        flex: 1,
                                        title: 'Class Menu'
                                    },
                                    {
                                        xtype: 'panel',
                                        height: 450,
                                        width: 200,
                                        flex: 1,
                                        title: 'Item Menu'
                                    },
                                    {
                                        xtype: 'panel',
                                        height: 450,
                                        width: 100,
                                        flex: 1,
                                        title: 'Calculator'
                                    },
                                    {
                                        xtype: 'panel',
                                        flex: 1,
                                        height: 450,
                                        width: 150,
                                        title: 'Result'
                                    }
                                ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});